# Generated by Django 4.2.2 on 2023-06-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_accion_aportador_comprainsumo_familiar_insumo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aportador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='user',
        ),
        migrations.AlterField(
            model_name='aportador',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
