# Generated by Django 4.2.2 on 2023-06-20 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_aportador_user_remove_familiar_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=40)),
                ('costo_plan', models.IntegerField()),
                ('descripcion_plan', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aportador',
            name='nro_tarjeta',
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('Debito', 'debito'), ('Credito', 'credito'), ('BitCoin', 'bitcoin')], max_length=30)),
                ('nro_tarjeta', models.IntegerField()),
                ('fecha_caducidad', models.DateField()),
                ('titular', models.CharField(max_length=40)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.aportador')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detallePago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.pago')),
                ('detallePlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.plan')),
            ],
        ),
    ]
