# Generated by Django 4.2.2 on 2023-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_plan_remove_aportador_nro_tarjeta_pago_detalleplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('Debito', 'Debito'), ('Credito', 'Credito'), ('BitCoin', 'Bitcoin')], default='debito', max_length=30),
        ),
    ]
